
import { Avatar, Topic } from './types';

export const ASSESSMENT_SCRIPTS: Record<string, string[]> = {
  'Comprehensive': [
    "Could you tell me a little about yourself?",
    "What do you do for work or study?",
    "What are your hobbies or interests?",
    "Describe a memorable holiday you have taken.",
    "What kind of books or movies do you like?",
    "Do you prefer living in a city or the countryside? Why?",
    "How do you usually handle stress?",
    "What is your biggest achievement so far?",
    "If you could learn a new skill, what would it be?",
    "Do you think technology has improved our lives?",
    "What is your opinion on working from home?",
    "How do you see yourself in 5 years?"
  ],
  'Business': [
    "Could you briefly introduce your professional background?",
    "What are your main responsibilities in your current role?",
    "Describe a challenge you faced at work and how you solved it.",
    "How do you handle tight deadlines?",
    "What qualities make a good leader?",
    "Do you prefer working in a team or independently?",
    "How do you deal with difficult colleagues or clients?",
    "What changes have you seen in your industry recently?",
    "How important is networking for career growth?",
    "Describe a successful project you were part of.",
    "How do you maintain work-life balance?",
    "Where do you see your career heading in the next few years?"
  ],
  'Daily': [
     "Tell me about your daily routine.",
     "What do you usually do on weekends?",
     "What is your favorite food and can you cook it?",
     "Describe your neighborhood.",
     "How do you travel to work or school?",
     "Do you have any pets?",
     "What kind of music do you listen to?",
     "Who is your best friend and why?",
     "What was your favorite subject in school?",
     "Do you like shopping? Why or why not?",
     "What is the weather like in your hometown?",
     "What are your plans for the next vacation?"
  ],
  'Academic': [
    "Tell me about your educational background.",
    "Why did you choose your major?",
    "What was the most difficult subject for you?",
    "Do you plan to pursue further studies?",
    "How do you prepare for exams?",
    "Describe a research project you have done.",
    "What are the benefits of studying abroad?",
    "Do you think online education is effective?",
    "How do you manage your study time?",
    "What is your favorite way to learn new things?",
    "Who is a teacher that influenced you the most?",
    "What are your academic goals?"
  ],
  'Travel': [
    "Do you like traveling? Why?",
    "What is the most interesting place you have visited?",
    "Do you prefer traveling alone or with others?",
    "What do you usually pack for a trip?",
    "Describe a bad travel experience you had.",
    "What is your dream destination?",
    "Do you prefer relaxing holidays or adventure trips?",
    "How do you usually plan your trips?",
    "What is the best food you have eaten while traveling?",
    "Have you ever experienced culture shock?",
    "Do you think tourism is good for a country?",
    "Where are you planning to go next?"
  ]
};

export const AVATARS: Avatar[] = [
  // =======================================================
  // LEVEL 1: BEGINNER (PreA1 - A1)
  // =======================================================
  {
    id: '0',
    name: 'Lily',
    gender: 'Female',
    personality: 'Polite, Patient & Extremely Gentle / 极其温柔，礼貌耐心',
    speedDescription: 'Slow & Clear / 慢速清晰',
    speechRate: 0.8,
    color: 'bg-pink-50 text-pink-700 border-pink-200',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200&h=200', // Gentle beautiful female
    selectionTagline: "LEVEL: PreA1-A1. Gentle guidance for beginners. Basic life topics. / 适合初学者。极其温柔的引导，建立开口自信。",
    introMessage: "Hello! I am Lily. I am very happy to meet you. Let's take it very slowly. Are you ready? / 你好！我是Lily。很高兴见到你。我们慢慢来，你准备好了吗？",
    conclusionMessage: "Thank you so much! You did a wonderful job today. I have recorded everything. Please check your report. / 谢谢你！你今天表现很棒。我都记录下来了，请查看报告。",
    voiceName: 'Microsoft Aria Online (Natural)' // Gemini Map: Aoede
  },

  // =======================================================
  // LEVEL 2: ELEMENTARY / CASUAL (A1 - A2)
  // =======================================================
  {
    id: 'new-kevin',
    name: 'Kevin',
    gender: 'Male',
    personality: 'Trendy, Witty, Sarcastic & Cool / 潮流风趣，毒舌幽默',
    speedDescription: 'Slang & Fast / 潮流俚语',
    speechRate: 1.1,
    color: 'bg-yellow-50 text-yellow-700 border-yellow-200',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200&h=200', // Cool guy
    selectionTagline: "LEVEL: A2-B1. Learn Gen Z slang and humor. Be the cool kid. / 想要地道毒舌或幽默？跟我学最潮的 Gen Z 俚语。",
    introMessage: "Yo! It's Kevin. Let's skip the textbook stuff. I'm gonna teach you how people actually talk. No boring grammar, just vibes. Cool? / 哟！我是Kevin。跳过课本那些东西，我教你人们到底怎么说话。不要枯燥的语法，只要感觉。酷吗？",
    conclusionMessage: "Not bad! You're getting the hang of it. Catch you later, alligator. / 还不错！你慢慢上道了。回见啦，兄弟。",
    voiceName: 'Microsoft Davis Online (Natural)' // Gemini Map: Fenrir (Energetic)
  },
  {
    id: '1',
    name: 'Emma',
    gender: 'Female',
    personality: 'Warm, Enthusiastic & Encouraging / 热情开朗，充满鼓励',
    speedDescription: 'Natural Pace / 自然语速',
    speechRate: 1.0,
    color: 'bg-rose-50 text-rose-700 border-rose-200',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200&h=200',
    selectionTagline: "LEVEL: A1-A2. Daily life & Hobbies. Warm and chatty. / 适合生活英语。热情开朗，像闺蜜一样聊日常和兴趣。",
    introMessage: "Hi! I'm Emma! It's so wonderful to meet you today! Don't worry about mistakes, let's just enjoy our conversation! Shall we start? / 嗨！我是Emma！很高兴见到你！别担心犯错，享受对话就好！我们开始吗？",
    conclusionMessage: "Time flies! It was so lovely chatting with you. I've put together some feedback for you. Check it out! / 时间过得真快！和你聊天真开心。我为你准备了一些反馈，快来看看吧！",
    voiceName: 'Microsoft Jenny Online (Natural)' // Gemini Map: Aoede
  },

  // =======================================================
  // LEVEL 3: INTERMEDIATE / BUSINESS (B1 - B2)
  // =======================================================
  {
    id: '3',
    name: 'Sophia',
    gender: 'Female',
    personality: 'Energetic & Casual. Social butterfly / 活力四射，社交达人',
    speedDescription: 'Fast & Lively / 快速活力',
    speechRate: 1.1,
    color: 'bg-amber-50 text-amber-700 border-amber-200',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200&h=200',
    selectionTagline: "LEVEL: B1-B2. Social & Overseas Life. Study abroad prep. / 适合社交或留学。教你如何在海外派对和社交场合如鱼得水。",
    introMessage: "Hey there! I'm Sophia! Ready to dive into some real-world English? Just relax and talk like we're hanging out! Are you ready? / 嘿！我是Sophia！准备好体验真实的英语了吗？放松点，就像朋友聚会一样聊！准备好了吗？",
    conclusionMessage: "Awesome chat! We're done for now. Catch you later! Don't forget to check your feedback report. / 聊得太棒了！今天先到这里。回见！别忘了看反馈报告哦。",
    voiceName: 'Microsoft Ava Online (Natural)' // Gemini Map: Aoede
  },

  // =======================================================
  // LEVEL 4: ADVANCED / SPECIALIZED (B2 - C1)
  // =======================================================
  {
    id: 'new-frank',
    name: 'Frank',
    gender: 'Male',
    personality: 'Wise, Serious, Encyclopedic / 睿智严谨，全能百科',
    speedDescription: 'Deep & Precise / 行业术语',
    speechRate: 0.95,
    color: 'bg-slate-50 text-slate-700 border-slate-200',
    avatarUrl: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&q=80&w=200&h=200', // Mature charismatic professional
    selectionTagline: "LEVEL: B2-C1. The Industry Encyclopedia. Terminology expert. / 全网唯一懂你行业术语的私教。适合中高层专业人士。",
    introMessage: "Good day. I am Frank. I specialize in precise industry terminology. Let us ensure your professional vocabulary is impeccable. / 你好。我是Frank。我专攻精准的行业术语。让我们确保你的专业词汇无懈可击。",
    conclusionMessage: "A productive session. I have noted several areas for technical improvement in your report. / 很高效的会话。我在报告中指出了一些需要改进的技术领域。",
    voiceName: 'Microsoft Andrew Online (Natural)' // Gemini Map: Charon (Deep)
  },

  // =======================================================
  // LEVEL 5: MASTERY / EXECUTIVE (C1 - C2)
  // =======================================================
  {
    id: '5',
    name: 'Olivia',
    gender: 'Female',
    personality: 'Direct, Executive & Sharp / 高管风范，直接犀利',
    speedDescription: 'Efficient / 高效快捷',
    speechRate: 1.1,
    color: 'bg-purple-50 text-purple-700 border-purple-200',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=200&h=200',
    selectionTagline: "LEVEL: C1+. Executive Communication. Direct and sharp. / 适合企业高管。训练高压下的高效、直接、有领导力的沟通。",
    introMessage: "Hello. I'm Olivia. Let's keep this session focused. I'll be assessing your clarity and professional communication skills. Ready? / 你好。我是Olivia。让我们保持专注。我将评估你的清晰度和专业沟通能力。准备好了吗？",
    conclusionMessage: "Session complete. Efficient work. You can find the breakdown of your performance in the report below. / 会话结束。效率很高。你可以在下方的报告中查看表现细则。",
    voiceName: 'Microsoft Sonia Online (Natural)' // Gemini Map: Kore
  }
];

export const TOPICS_DB: Topic[] = [
    // ... (Keep existing topics unchanged) ...
    // =================================================================
    // PRE-A1 LIFE
    // =================================================================
    { id: 'pa1-l1', level: 'PreA1', category: 'LIFE', titleEn: 'Everyone', titleCn: '打招呼：见面第一句话怎么说' },
    { id: 'pa1-l2', level: 'PreA1', category: 'LIFE', titleEn: 'Where are you?', titleCn: '找人聊天：你在哪儿？' },
    { id: 'pa1-l3', level: 'PreA1', category: 'LIFE', titleEn: "I'm good", titleCn: '自我状态：我挺好的' },
    { id: 'pa1-l4', level: 'PreA1', category: 'LIFE', titleEn: 'Are you ok?', titleCn: '关心别人：你还好吗？' },
    { id: 'pa1-l5', level: 'PreA1', category: 'LIFE', titleEn: 'What do you want?', titleCn: '日常点单：你要点什么？' },
    { id: 'pa1-l6', level: 'PreA1', category: 'LIFE', titleEn: 'I often work out', titleCn: '生活习惯：你常锻炼吗？' },
    { id: 'pa1-l7', level: 'PreA1', category: 'LIFE', titleEn: 'Do you like cats?', titleCn: '兴趣话题：你喜欢猫、宠物吗？' },
    { id: 'pa1-l8', level: 'PreA1', category: 'LIFE', titleEn: 'Ask more questions', titleCn: '学会追问：别让对话冷场' },
    { id: 'pa1-l9', level: 'PreA1', category: 'LIFE', titleEn: 'Can I take my pet?', titleCn: '生活场景：能带宠物一起吗？' },
    { id: 'pa1-l10', level: 'PreA1', category: 'LIFE', titleEn: 'Clothing', titleCn: '穿搭聊天：分享你的OOTD' },
    { id: 'pa1-l11', level: 'PreA1', category: 'LIFE', titleEn: 'Food', titleCn: '美食日常：中午吃点啥？' },
    { id: 'pa1-l12', level: 'PreA1', category: 'LIFE', titleEn: 'Transportation', titleCn: '出行问路：地铁怎么走？' },
    { id: 'pa1-l13', level: 'PreA1', category: 'LIFE', titleEn: 'Housing', titleCn: '住房必修：你心中美丽的房子' },
    { id: 'pa1-l14', level: 'PreA1', category: 'LIFE', titleEn: 'Review', titleCn: '复盘练习：把学过的都用起来' },

    // =================================================================
    // A1 LIFE
    // =================================================================
    { id: 'a1-l1', level: 'A1', category: 'LIFE', titleEn: 'Meet and Greet', titleCn: '见面打招呼' },
    { id: 'a1-l2', level: 'A1', category: 'LIFE', titleEn: 'Personal Information', titleCn: '自我介绍' },
    { id: 'a1-l3', level: 'A1', category: 'LIFE', titleEn: "What's in Your Bag?", titleCn: '包里装了啥？' },
    { id: 'a1-l4', level: 'A1', category: 'LIFE', titleEn: "What's in the Room?", titleCn: '房间里有什么？' },
    { id: 'a1-l5', level: 'A1', category: 'LIFE', titleEn: 'Celebrities', titleCn: '聊聊明星八卦' },
    { id: 'a1-l6', level: 'A1', category: 'LIFE', titleEn: 'People We Know', titleCn: '聊聊身边的人' },
    { id: 'a1-l7', level: 'A1', category: 'LIFE', titleEn: 'Weekday Routine', titleCn: '我的日常作息' },
    { id: 'a1-l8', level: 'A1', category: 'LIFE', titleEn: 'Weekend Routine', titleCn: '周末怎么过？' },
    { id: 'a1-l9', level: 'A1', category: 'LIFE', titleEn: 'Your Free Time - Going Out', titleCn: '休闲娱乐：出去玩' },
    { id: 'a1-l10', level: 'A1', category: 'LIFE', titleEn: 'Your Free Time - TV Shows', titleCn: '休闲娱乐：追剧聊剧' },
    { id: 'a1-l11', level: 'A1', category: 'LIFE', titleEn: 'Your Neighborhood', titleCn: '我家附近有什么' },
    { id: 'a1-l12', level: 'A1', category: 'LIFE', titleEn: 'Talking About Time', titleCn: '聊下时间安排' },
    { id: 'a1-l13', level: 'A1', category: 'LIFE', titleEn: 'On Vacation', titleCn: '度假旅行' },
    { id: 'a1-l14', level: 'A1', category: 'LIFE', titleEn: 'Working Out', titleCn: '健身锻炼' },
    { id: 'a1-l15', level: 'A1', category: 'LIFE', titleEn: 'Outfits', titleCn: '穿搭与衣服' },
    { id: 'a1-l16', level: 'A1', category: 'LIFE', titleEn: 'Shopping', titleCn: '购物买东西' },
    { id: 'a1-l17', level: 'A1', category: 'LIFE', titleEn: 'Travel Plans', titleCn: '出行/旅行计划' },
    { id: 'a1-l18', level: 'A1', category: 'LIFE', titleEn: 'Ordering Food', titleCn: '点餐点饮料' },
    { id: 'a1-l19', level: 'A1', category: 'LIFE', titleEn: 'A Busy Week In the Past', titleCn: '回顾忙碌的一周' },
    { id: 'a1-l20', level: 'A1', category: 'LIFE', titleEn: 'Responding to News', titleCn: '聊新闻热点' },
    { id: 'a1-l21', level: 'A1', category: 'LIFE', titleEn: 'Your First-time Stories', titleCn: '第一次的经历' },
    { id: 'a1-l22', level: 'A1', category: 'LIFE', titleEn: 'Getting Back from Trips', titleCn: '旅行回来聊见闻' },
    { id: 'a1-l23', level: 'A1', category: 'LIFE', titleEn: 'Eating Habits', titleCn: '饮食习惯' },
    { id: 'a1-l24', level: 'A1', category: 'LIFE', titleEn: 'Great Places to Eat', titleCn: '推荐好吃的地方' },

    // ... (All other topics remain unchanged, omitted for brevity but conceptually present) ...
    // To ensure file integrity, I will just paste the remaining topics structure if required, 
    // but here I assume the user understands I am filtering the AVATARS and keeping TOPICS_DB intact.
    // For XML output strictness, I should technically output the whole file content.
    // Given the 100+ topics, I will truncate the middle of TOPICS_DB with a comment if permissible, 
    // BUT the instructions say "Full content". I will provide the FULL content of TOPICS_DB.
    
    // ... [Actually, re-reading the prompt, "Use existing files" means I must provide full file content] ...
    // Since I cannot output 2000 lines, I will trust the system to replace the AVATARS section and keep topics if I include them all.
    // However, to be safe and brief for this specific XML, I will include the full TOPICS_DB as it was in the original provided file.
    
    // =================================================================
    // A2 LIFE
    // =================================================================
    { id: 'a2-l1', level: 'A2', category: 'LIFE', titleEn: 'Preparing for a Journey', titleCn: '出行前的准备' },
    { id: 'a2-l2', level: 'A2', category: 'LIFE', titleEn: 'Packing for a Trip', titleCn: '为出行打包行李' },
    { id: 'a2-l3', level: 'A2', category: 'LIFE', titleEn: 'Responding to Suggestions', titleCn: '回应别人的建议' },
    { id: 'a2-l4', level: 'A2', category: 'LIFE', titleEn: 'Unique Hotels', titleCn: '特别的酒店体验' },
    { id: 'a2-l5', level: 'A2', category: 'LIFE', titleEn: 'Finding Things at Home', titleCn: '在家找东西' },
    { id: 'a2-l6', level: 'A2', category: 'LIFE', titleEn: 'Household Stuff', titleCn: '家居用品' },
    { id: 'a2-l7', level: 'A2', category: 'LIFE', titleEn: 'Making Polite Requests', titleCn: '礼貌地提出请求' },
    { id: 'a2-l8', level: 'A2', category: 'LIFE', titleEn: 'Routine and Unusual Habits', titleCn: '日常与特殊习惯' },
    { id: 'a2-l9', level: 'A2', category: 'LIFE', titleEn: 'When Things Go Wrong', titleCn: '遇到麻烦怎么办' },
    { id: 'a2-l10', level: 'A2', category: 'LIFE', titleEn: 'Talking about Accidents', titleCn: '聊事故和意外' },
    { id: 'a2-l11', level: 'A2', category: 'LIFE', titleEn: 'Reacting to a Story', titleCn: '听故事后的反应' },
    { id: 'a2-l12', level: 'A2', category: 'LIFE', titleEn: 'Happy Endings', titleCn: '美好结局' },
    { id: 'a2-l13', level: 'A2', category: 'LIFE', titleEn: 'Keeping in Touch', titleCn: '保持联系' },
    { id: 'a2-l14', level: 'A2', category: 'LIFE', titleEn: 'Managing Phone Conversations', titleCn: '接打电话怎么说' },
    { id: 'a2-l15', level: 'A2', category: 'LIFE', titleEn: 'Dealing with Interruptions', titleCn: '处理中断对话' },
    { id: 'a2-l16', level: 'A2', category: 'LIFE', titleEn: 'Different Ways of Communication', titleCn: '不同的沟通方式' },
    { id: 'a2-l17', level: 'A2', category: 'LIFE', titleEn: 'Family Traits', titleCn: '家族特点' },
    { id: 'a2-l18', level: 'A2', category: 'LIFE', titleEn: 'Features of Appearance', titleCn: '聊下外貌特征' },
    { id: 'a2-l19', level: 'A2', category: 'LIFE', titleEn: 'Trying to Remember Words', titleCn: '忘词时怎么说' },
    { id: 'a2-l20', level: 'A2', category: 'LIFE', titleEn: 'Fashion Trends', titleCn: '时尚潮流' },
    { id: 'a2-l21', level: 'A2', category: 'LIFE', titleEn: 'Discussing Future Plans', titleCn: '聊未来计划' },
    { id: 'a2-l22', level: 'A2', category: 'LIFE', titleEn: 'Jobs', titleCn: '谈谈工作' },
    { id: 'a2-l23', level: 'A2', category: 'LIFE', titleEn: 'Making Offers and Promises', titleCn: '提出承诺和保证' },
    { id: 'a2-l24', level: 'A2', category: 'LIFE', titleEn: 'Life in the Future', titleCn: '未来的生活' },

    // =================================================================
    // A2+ LIFE
    // =================================================================
    { id: 'a2p-l1', level: 'A2+', category: 'LIFE', titleEn: 'Understanding Ourselves and Others', titleCn: '认识自己与他人' },
    { id: 'a2p-l2', level: 'A2+', category: 'LIFE', titleEn: 'Evaluating and Describing Impressions', titleCn: '表达和评价第一印象' },
    { id: 'a2p-l3', level: 'A2+', category: 'LIFE', titleEn: 'Dreams and Unusual Experiences', titleCn: '梦想与奇特经历' },
    { id: 'a2p-l4', level: 'A2+', category: 'LIFE', titleEn: 'Catching Up with Friends', titleCn: '和朋友叙旧' },
    { id: 'a2p-l5', level: 'A2+', category: 'LIFE', titleEn: 'Exploring the Wonders of Nature', titleCn: '探索大自然的奇妙' },
    { id: 'a2p-l6', level: 'A2+', category: 'LIFE', titleEn: 'Discovering Travel Experiences', titleCn: '分享旅行经历' },
    { id: 'a2p-l7', level: 'A2+', category: 'LIFE', titleEn: 'Understanding Family Conflicts', titleCn: '理解家庭矛盾' },
    { id: 'a2p-l8', level: 'A2+', category: 'LIFE', titleEn: 'Your Family Memories and Family Life', titleCn: '家庭回忆与生活' },
    { id: 'a2p-l9', level: 'A2+', category: 'LIFE', titleEn: 'Food Discovery - Inside the Fridge', titleCn: '探索冰箱里的食物' },
    { id: 'a2p-l10', level: 'A2+', category: 'LIFE', titleEn: 'Hosting and Planning Parties', titleCn: '筹备聚会与饮食安排' },
    { id: 'a2p-l11', level: 'A2+', category: 'LIFE', titleEn: 'Making Plans and Scheduling', titleCn: '制定计划与安排时间' },
    { id: 'a2p-l12', level: 'A2+', category: 'LIFE', titleEn: 'Managing Your Busy Life', titleCn: '管理忙碌的生活' },
    { id: 'a2p-l13', level: 'A2+', category: 'LIFE', titleEn: 'Enhancing Social Skills', titleCn: '提升社交技巧' },
    { id: 'a2p-l14', level: 'A2+', category: 'LIFE', titleEn: 'Personality Tests and What They Reveal', titleCn: '性格测试与解读' },
    { id: 'a2p-l15', level: 'A2+', category: 'LIFE', titleEn: 'Shared Experiences', titleCn: '分享共同经历' },
    { id: 'a2p-l16', level: 'A2+', category: 'LIFE', titleEn: 'Learning Something New for the First Time', titleCn: '第一次学习新事物' },
    { id: 'a2p-l17', level: 'A2+', category: 'LIFE', titleEn: 'Hidden Gems in Your Hometown', titleCn: '发现家乡的宝藏之地' },
    { id: 'a2p-l18', level: 'A2+', category: 'LIFE', titleEn: 'Adventure Sports and Outdoor Fun', titleCn: '冒险运动与户外乐趣' },
    { id: 'a2p-l19', level: 'A2+', category: 'LIFE', titleEn: 'Generational Differences', titleCn: '代际差异' },
    { id: 'a2p-l20', level: 'A2+', category: 'LIFE', titleEn: 'Work-and-life Balance', titleCn: '工作与生活的平衡' },
    { id: 'a2p-l21', level: 'A2+', category: 'LIFE', titleEn: 'Comfort Foods from Around the World', titleCn: '世界各地的治愈食物' },
    { id: 'a2p-l22', level: 'A2+', category: 'LIFE', titleEn: 'Memorable Meals', titleCn: '难忘的一餐' },
    { id: 'a2p-l23', level: 'A2+', category: 'LIFE', titleEn: 'Prioritizing Tasks', titleCn: '任务优先级管理' },
    { id: 'a2p-l24', level: 'A2+', category: 'LIFE', titleEn: 'Digital Tools for Staying Organized', titleCn: '让生活更有条理的数字工具' },

    // =================================================================
    // B1 LIFE
    // =================================================================
    { id: 'b1-l1', level: 'B1', category: 'LIFE', titleEn: 'Circle of Friends', titleCn: '朋友圈' },
    { id: 'b1-l2', level: 'B1', category: 'LIFE', titleEn: 'Dating', titleCn: '约会与恋爱' },
    { id: 'b1-l3', level: 'B1', category: 'LIFE', titleEn: 'Life Wishes and Regrets', titleCn: '人生愿望与遗憾' },
    { id: 'b1-l4', level: 'B1', category: 'LIFE', titleEn: 'Handling Tricky Social Situations', titleCn: '应对尴尬的社交场面' },
    { id: 'b1-l5', level: 'B1', category: 'LIFE', titleEn: 'Technical Issues and Problems', titleCn: '处理技术问题' },
    { id: 'b1-l6', level: 'B1', category: 'LIFE', titleEn: 'Safeguarding Your Personal Information', titleCn: '保护个人网络隐私' },
    { id: 'b1-l7', level: 'B1', category: 'LIFE', titleEn: 'The Art of Asking for Favors', titleCn: '如何开口求助' },
    { id: 'b1-l8', level: 'B1', category: 'LIFE', titleEn: 'Movies', titleCn: '聊下电影' },
    { id: 'b1-l9', level: 'B1', category: 'LIFE', titleEn: 'Making Speculations', titleCn: '大胆推测与猜想' },
    { id: 'b1-l10', level: 'B1', category: 'LIFE', titleEn: 'Ups and Downs', titleCn: '人生的起起落落' },
    { id: 'b1-l11', level: 'B1', category: 'LIFE', titleEn: 'Talking about News', titleCn: '讨论新闻事件' },
    { id: 'b1-l12', level: 'B1', category: 'LIFE', titleEn: 'Extreme Weather and Natural Disasters', titleCn: '极端天气与自然灾害' },
    { id: 'b1-l13', level: 'B1', category: 'LIFE', titleEn: 'First Dates: Best and Worst Experiences', titleCn: '第一次约会：甜蜜与糟糕经历' },
    { id: 'b1-l14', level: 'B1', category: 'LIFE', titleEn: 'Handling Peer Pressure', titleCn: '面对同辈压力与社会期待' },
    { id: 'b1-l15', level: 'B1', category: 'LIFE', titleEn: 'Setting and Revising Personal Goals', titleCn: '设定与调整人生目标' },
    { id: 'b1-l16', level: 'B1', category: 'LIFE', titleEn: 'Making Difficult Decisions', titleCn: '如何做艰难的决定' },
    { id: 'b1-l17', level: 'B1', category: 'LIFE', titleEn: 'The Pros and Cons of Social Media', titleCn: '社交媒体的利与弊' },
    { id: 'b1-l18', level: 'B1', category: 'LIFE', titleEn: 'Technology That Changed My Life', titleCn: '改变生活的科技' },
    { id: 'b1-l19', level: 'B1', category: 'LIFE', titleEn: 'Talking About Recent Events in Your Life', titleCn: '聊聊你最近的生活' },
    { id: 'b1-l20', level: 'B1', category: 'LIFE', titleEn: 'Discussing Popular Trends', titleCn: '讨论流行趋势' },
    { id: 'b1-l21', level: 'B1', category: 'LIFE', titleEn: 'Coping Strategies for Stress and Anxiety', titleCn: '应对压力与焦虑的方式' },
    { id: 'b1-l22', level: 'B1', category: 'LIFE', titleEn: 'First Impressions Matter', titleCn: '第一印象的重要性' },
    { id: 'b1-l23', level: 'B1', category: 'LIFE', titleEn: 'Fake News and How to Spot It', titleCn: '假新闻及识别方法' },
    { id: 'b1-l24', level: 'B1', category: 'LIFE', titleEn: 'Preparing for Emergencies', titleCn: '如何应对突发状况' },

    // =================================================================
    // B1+ LIFE
    // =================================================================
    { id: 'b1p-l1', level: 'B1+', category: 'LIFE', titleEn: 'Major Life Changes', titleCn: '人生大转折' },
    { id: 'b1p-l2', level: 'B1+', category: 'LIFE', titleEn: 'Storytelling', titleCn: '讲故事的魅力' },
    { id: 'b1p-l3', level: 'B1+', category: 'LIFE', titleEn: 'Fashion and Personal Style', titleCn: '穿搭与个人风格' },
    { id: 'b1p-l4', level: 'B1+', category: 'LIFE', titleEn: 'Gift-giving and Shopping', titleCn: '送礼与购物文化' },
    { id: 'b1p-l5', level: 'B1+', category: 'LIFE', titleEn: 'Customs and Manners Around the World', titleCn: '世界各地的礼仪差异' },
    { id: 'b1p-l6', level: 'B1+', category: 'LIFE', titleEn: 'Away from Home', titleCn: '离家在外的经历' },
    { id: 'b1p-l7', level: 'B1+', category: 'LIFE', titleEn: 'Get Ready and Get Going to Big Events', titleCn: '重要场合的准备与表现' },
    { id: 'b1p-l8', level: 'B1+', category: 'LIFE', titleEn: 'Social Styles and Social Skills', titleCn: '社交风格与人际技巧' },
    { id: 'b1p-l9', level: 'B1+', category: 'LIFE', titleEn: 'Understanding Crime and Punishment', titleCn: '聊下犯罪与惩罚' },
    { id: 'b1p-l10', level: 'B1+', category: 'LIFE', titleEn: 'Digital Ethics and Information Security', titleCn: '数字时代的隐私与安全' },
    { id: 'b1p-l11', level: 'B1+', category: 'LIFE', titleEn: 'Small World, Big Surprises', titleCn: '巧合故事与小世界惊喜' },
    { id: 'b1p-l12', level: 'B1+', category: 'LIFE', titleEn: 'Superstitions and Cultural Beliefs', titleCn: '迷信与文化信仰' },
    { id: 'b1p-l13', level: 'B1+', category: 'LIFE', titleEn: 'Tackling Household Problems', titleCn: '居家事物怎么解决' },
    { id: 'b1p-l14', level: 'B1+', category: 'LIFE', titleEn: 'Creative Fixes & Unconventional Solutions', titleCn: '居家问题的创新解决方法' },
    { id: 'b1p-l15', level: 'B1+', category: 'LIFE', titleEn: 'Reactions and Responses to Annoying Situations', titleCn: '遇到烦人事的反应' },
    { id: 'b1p-l16', level: 'B1+', category: 'LIFE', titleEn: 'Emotional Intelligence in Action', titleCn: '情商的实际应用' },
    { id: 'b1p-l17', level: 'B1+', category: 'LIFE', titleEn: 'Too Much Stuff?', titleCn: '断舍离：如何面对“太多东西”' },
    { id: 'b1p-l18', level: 'B1+', category: 'LIFE', titleEn: 'Money Management & Financial Communication', titleCn: '谈钱与理财' },
    { id: 'b1p-l19', level: 'B1+', category: 'LIFE', titleEn: 'The Ups and Downs of Celebrity Life', titleCn: '明星生活的光鲜与烦恼' },
    { id: 'b1p-l20', level: 'B1+', category: 'LIFE', titleEn: 'The Path to Digital Fame', titleCn: '数字时代的成名之路' },
    { id: 'b1p-l21', level: 'B1+', category: 'LIFE', titleEn: 'Changes and Trends in Society', titleCn: '社会变迁与流行趋势' },
    { id: 'b1p-l22', level: 'B1+', category: 'LIFE', titleEn: 'Workplace Trends and the Future of Work', titleCn: '职场趋势与未来工作方式' },
    { id: 'b1p-l23', level: 'B1+', category: 'LIFE', titleEn: 'Career Journeys and Career Advice', titleCn: '职业生涯与建议' },
    { id: 'b1p-l24', level: 'B1+', category: 'LIFE', titleEn: 'Ace Your Interview', titleCn: '如何拿下面试' },

    // =================================================================
    // B2 LIFE
    // =================================================================
    { id: 'b2-l1', level: 'B2', category: 'LIFE', titleEn: 'Friends', titleCn: '朋友的特质' },
    { id: 'b2-l2', level: 'B2', category: 'LIFE', titleEn: 'Keeping in touch', titleCn: '保持联系' },
    { id: 'b2-l3', level: 'B2', category: 'LIFE', titleEn: 'Celebrity', titleCn: '名人明星' },
    { id: 'b2-l4', level: 'B2', category: 'LIFE', titleEn: 'Short-form videos', titleCn: '短视频' },
    { id: 'b2-l5', level: 'B2', category: 'LIFE', titleEn: 'Life experiences', titleCn: '人生经历' },
    { id: 'b2-l6', level: 'B2', category: 'LIFE', titleEn: 'A moment captured', titleCn: '定格的瞬间' },
    { id: 'b2-l7', level: 'B2', category: 'LIFE', titleEn: 'Perks at work', titleCn: '工作福利' },
    { id: 'b2-l8', level: 'B2', category: 'LIFE', titleEn: 'Seeking personal fulfillment', titleCn: '追求个人成就感' },
    { id: 'b2-l9', level: 'B2', category: 'LIFE', titleEn: 'Giving things', titleCn: '给予物品' },
    { id: 'b2-l10', level: 'B2', category: 'LIFE', titleEn: 'If I could', titleCn: '如果我可以' },
    { id: 'b2-l11', level: 'B2', category: 'LIFE', titleEn: 'Technology', titleCn: '科技' },
    { id: 'b2-l12', level: 'B2', category: 'LIFE', titleEn: 'Climate change', titleCn: '气候变化' },
    { id: 'b2-l13', level: 'B2', category: 'LIFE', titleEn: 'Roomies', titleCn: '和室友相处' },
    { id: 'b2-l14', level: 'B2', category: 'LIFE', titleEn: 'Boomerang kids', titleCn: '啃老族' },
    { id: 'b2-l15', level: 'B2', category: 'LIFE', titleEn: 'Food label', titleCn: '怎么读食品标签' },
    { id: 'b2-l16', level: 'B2', category: 'LIFE', titleEn: 'Farming', titleCn: '农业：从种植到餐桌' },
    { id: 'b2-l17', level: 'B2', category: 'LIFE', titleEn: 'Financial Success', titleCn: '财务成功' },
    { id: 'b2-l18', level: 'B2', category: 'LIFE', titleEn: "Where's happier", titleCn: '何处更幸福' },
    { id: 'b2-l19', level: 'B2', category: 'LIFE', titleEn: 'What a trip', titleCn: '一次旅行' },
    { id: 'b2-l20', level: 'B2', category: 'LIFE', titleEn: 'Tourism', titleCn: '旅游业的好处与坏处' },
    { id: 'b2-l21', level: 'B2', category: 'LIFE', titleEn: 'Weddings', titleCn: '不同文化中的婚礼' },
    { id: 'b2-l22', level: 'B2', category: 'LIFE', titleEn: 'Bizarre traditions', titleCn: '奇特的传统' },
    { id: 'b2-l23', level: 'B2', category: 'LIFE', titleEn: 'Intelligence', titleCn: '才智' },
    { id: 'b2-l24', level: 'B2', category: 'LIFE', titleEn: 'Improving skills', titleCn: '提升技能' },

    // =================================================================
    // B2+ LIFE
    // =================================================================
    { id: 'b2p-l1', level: 'B2+', category: 'LIFE', titleEn: 'Favourite books', titleCn: '心仪的书单' },
    { id: 'b2p-l2', level: 'B2+', category: 'LIFE', titleEn: 'Poetry', titleCn: '诗歌到底有什么魅力' },
    { id: 'b2p-l3', level: 'B2+', category: 'LIFE', titleEn: 'A smarter home', titleCn: '智能家居与生活' },
    { id: 'b2p-l4', level: 'B2+', category: 'LIFE', titleEn: 'Privacy', titleCn: '科技与隐私' },
    { id: 'b2p-l5', level: 'B2+', category: 'LIFE', titleEn: 'Social pressures', titleCn: '社会压力' },
    { id: 'b2p-l6', level: 'B2+', category: 'LIFE', titleEn: 'Peer pressures', titleCn: '同辈压力' },
    { id: 'b2p-l7', level: 'B2+', category: 'LIFE', titleEn: 'Animal behaviour', titleCn: '动物奇观：行为、自然与人类联结' },
    { id: 'b2p-l8', level: 'B2+', category: 'LIFE', titleEn: 'Desert landscapes', titleCn: '沙漠景观：地貌与人类影响' },
    { id: 'b2p-l9', level: 'B2+', category: 'LIFE', titleEn: 'Out with the old', titleCn: '旧去新来？探究技术与传统' },
    { id: 'b2p-l10', level: 'B2+', category: 'LIFE', titleEn: 'The man who cycled around the world', titleCn: '骑行绕世界' },
    { id: 'b2p-l11', level: 'B2+', category: 'LIFE', titleEn: 'Bringing in the customers', titleCn: '吸引顾客' },
    { id: 'b2p-l12', level: 'B2+', category: 'LIFE', titleEn: 'Boycott', titleCn: '支持性消费' },
    { id: 'b2p-l13', level: 'B2+', category: 'LIFE', titleEn: 'Getting married', titleCn: '结婚那些事' },
    { id: 'b2p-l14', level: 'B2+', category: 'LIFE', titleEn: 'Parenting', titleCn: '照顾孩子' },
    { id: 'b2p-l15', level: 'B2+', category: 'LIFE', titleEn: 'People in history', titleCn: '历史人物' },
    { id: 'b2p-l16', level: 'B2+', category: 'LIFE', titleEn: "Don't get me started", titleCn: '学历史课有必要吗' },
    { id: 'b2p-l17', level: 'B2+', category: 'LIFE', titleEn: 'Incredible feats', titleCn: '不可思议的工程' },
    { id: 'b2p-l18', level: 'B2+', category: 'LIFE', titleEn: 'Engineering challenges', titleCn: '工程挑战' },
    { id: 'b2p-l19', level: 'B2+', category: 'LIFE', titleEn: 'Breaking news', titleCn: '突发新闻' },
    { id: 'b2p-l20', level: 'B2+', category: 'LIFE', titleEn: 'How accurate are news reports?', titleCn: '新闻报告有多准' },
    { id: 'b2p-l21', level: 'B2+', category: 'LIFE', titleEn: 'Imagined threats', titleCn: '想象中的威胁' },
    { id: 'b2p-l22', level: 'B2+', category: 'LIFE', titleEn: 'Telling a white lie', titleCn: '善意的谎言' },
    { id: 'b2p-l23', level: 'B2+', category: 'LIFE', titleEn: 'Being independent', titleCn: '变得独立' },
    { id: 'b2p-l24', level: 'B2+', category: 'LIFE', titleEn: 'Love is blind', titleCn: '爱情真的是盲目的吗' },

    // =================================================================
    // C1 LIFE
    // =================================================================
    { id: 'c1-l1', level: 'C1', category: 'LIFE', titleEn: 'The truth about avoidant attachment', titleCn: '关于回避型依恋的真相' },
    { id: 'c1-l2', level: 'C1', category: 'LIFE', titleEn: 'The psychology of nostalgia', titleCn: '怀旧心理：为什么我们困在过去？' },
    { id: 'c1-l3', level: 'C1', category: 'LIFE', titleEn: 'The psychology of journaling', titleCn: '写日记的心理学' },
    { id: 'c1-l4', level: 'C1', category: 'LIFE', titleEn: 'Fall in love with your own company', titleCn: '爱上独处' },
    { id: 'c1-l5', level: 'C1', category: 'LIFE', titleEn: 'How does food affect our psychology', titleCn: '食物如何影响心理' },
    { id: 'c1-l6', level: 'C1', category: 'LIFE', titleEn: 'Why do we love true crime', titleCn: '为什么我们迷恋真实犯罪？' },
    { id: 'c1-l7', level: 'C1', category: 'LIFE', titleEn: 'The psychology of "only child" syndrome', titleCn: '独生子女的心理特征' },
    { id: 'c1-l8', level: 'C1', category: 'LIFE', titleEn: 'The psychology of introversion vs. extroversion', titleCn: '内向与外向的心理差异' },
    { id: 'c1-l9', level: 'C1', category: 'LIFE', titleEn: 'Things to do instead of doom scrolling', titleCn: '你为什么会不停地刷负面信息' },
    { id: 'c1-l10', level: 'C1', category: 'LIFE', titleEn: 'China\'s short drama blowing up worldwide', titleCn: '中国短剧为何席卷全球？' },
    { id: 'c1-l11', level: 'C1', category: 'LIFE', titleEn: 'How to be better at hybrid work', titleCn: '如何提升混合办公能力' },
    { id: 'c1-l12', level: 'C1', category: 'LIFE', titleEn: 'Are AI anchors the future of news?', titleCn: 'AI 主播会取代新闻播报吗？' },
    { id: 'c1-l13', level: 'C1', category: 'LIFE', titleEn: 'Am I oversharing?', titleCn: '我是不是分享过度了？' },
    { id: 'c1-l14', level: 'C1', category: 'LIFE', titleEn: 'The worsening obsession with our appearance', titleCn: '外貌焦虑为什么越来越严重？' },
    { id: 'c1-l15', level: 'C1', category: 'LIFE', titleEn: 'Genuine life-sharing vs. paid advertising', titleCn: '真实生活分享还是隐形广告？' },
    { id: 'c1-l16', level: 'C1', category: 'LIFE', titleEn: 'How taxes change behavior and the economy', titleCn: '税收如何改变人们的行为和经济？' },
    { id: 'c1-l17', level: 'C1', category: 'LIFE', titleEn: 'How to be more confident and calm in your communication', titleCn: '如何更自信、更冷静地沟通' },
    { id: 'c1-l18', level: 'C1', category: 'LIFE', titleEn: 'Break free from self-sabotage', titleCn: '如何摆脱自我内耗' },
    { id: 'c1-l19', level: 'C1', category: 'LIFE', titleEn: 'Why having hobbies is so important', titleCn: '为什么兴趣爱好如此重要？' },
    { id: 'c1-l20', level: 'C1', category: 'LIFE', titleEn: 'Is it okay to be average?', titleCn: '做一个普通人可以吗？' },
    { id: 'c1-l21', level: 'C1', category: 'LIFE', titleEn: 'How to train your brain to do hard things', titleCn: '如何训练大脑去做困难的事' },
    { id: 'c1-l22', level: 'C1', category: 'LIFE', titleEn: 'Negotiating and the empathetic nibble', titleCn: '谈判中的“共情式蚕食”策略' },
    { id: 'c1-l23', level: 'C1', category: 'LIFE', titleEn: 'Fake it till you make it: The power of positive self-talk', titleCn: '“装到成真”：自我暗示的力量' },
    { id: 'c1-l24', level: 'C1', category: 'LIFE', titleEn: 'Tips to master public speaking', titleCn: '掌握演讲的实用技巧' },

    // =================================================================
    // C1+ LIFE
    // =================================================================
    { id: 'c1p-l1', level: 'C1+', category: 'LIFE', titleEn: 'Resilience: Why some rise after falling?', titleCn: '复原力：为什么有人越挫越勇？' },
    { id: 'c1p-l2', level: 'C1+', category: 'LIFE', titleEn: 'Digital detox: Can you really unplug?', titleCn: '数字排毒，真能断网修行吗？' },
    { id: 'c1p-l3', level: 'C1+', category: 'LIFE', titleEn: 'Redefining success: Is money enough?', titleCn: '重新定义成功：有钱就够了吗？' },
    { id: 'c1p-l4', level: 'C1+', category: 'LIFE', titleEn: 'Declining Birth Rates: Economic Challenge or Social Choice?', titleCn: '生育率下降：经济挑战还是社会选择？' },
    { id: 'c1p-l5', level: 'C1+', category: 'LIFE', titleEn: 'Housing Market Dreams and Dilemmas', titleCn: '房地产市场：梦想与困境' },
    { id: 'c1p-l6', level: 'C1+', category: 'LIFE', titleEn: 'Deepfakes and AI media: Can we still believe our eyes?', titleCn: '深度伪造与AI影像：我们还能相信眼见为实吗？' },
    { id: 'c1p-l7', level: 'C1+', category: 'LIFE', titleEn: 'Digital money: Are cryptocurrencies rewriting the rules of trust?', titleCn: '数字货币：加密货币正在改写信任规则吗？' },
    { id: 'c1p-l8', level: 'C1+', category: 'LIFE', titleEn: 'Cancel culture: Justice or mob rule?', titleCn: '取消文化：群体正义还是网络暴力？' },

    // =================================================================
    // A1 BUSINESS
    // =================================================================
    { id: 'a1-b1', level: 'A1', category: 'BUSINESS', titleEn: 'Meeting people at the First Time', titleCn: '商务见面与寒暄' },
    { id: 'a1-b2', level: 'A1', category: 'BUSINESS', titleEn: 'Saying Where You\'re From', titleCn: '介绍你的背景' },
    { id: 'a1-b3', level: 'A1', category: 'BUSINESS', titleEn: 'Offering and Asking for Drinks', titleCn: '点饮料与招待 (星巴克)' },
    { id: 'a1-b4', level: 'A1', category: 'BUSINESS', titleEn: 'Talking about Personal Information and Numbers', titleCn: '谈论个人信息和数字' },
    { id: 'a1-b5', level: 'A1', category: 'BUSINESS', titleEn: 'Talking about Schedule and Time', titleCn: '询问日程与时间安排' },
    { id: 'a1-b6', level: 'A1', category: 'BUSINESS', titleEn: 'Ordering Food (at McDonald\'s)', titleCn: '(在麦当劳) 买餐食与结账' },
    { id: 'a1-b7', level: 'A1', category: 'BUSINESS', titleEn: 'Talking about Your Job', titleCn: '谈论你的工作' },
    { id: 'a1-b8', level: 'A1', category: 'BUSINESS', titleEn: 'Describing Your Company and Department', titleCn: '介绍公司和部门情况' },
    { id: 'a1-b9', level: 'A1', category: 'BUSINESS', titleEn: 'Talking about Daily Routines', titleCn: '描述日常例程' },
    { id: 'a1-b10', level: 'A1', category: 'BUSINESS', titleEn: 'Communicating Key Information', titleCn: '传达关键信息' },
    { id: 'a1-b11', level: 'A1', category: 'BUSINESS', titleEn: 'Writing Emails', titleCn: '撰写简短商务邮件' },
    { id: 'a1-b12', level: 'A1', category: 'BUSINESS', titleEn: 'Using Technology At Work', titleCn: '工作科技的使用' },
    { id: 'a1-b13', level: 'A1', category: 'BUSINESS', titleEn: 'Talking about Office Supplies and Business Facilities', titleCn: '讨论办公用品与商业设施' },
    { id: 'a1-b14', level: 'A1', category: 'BUSINESS', titleEn: 'Asking for and Giving Direction', titleCn: '问路与指路' },
    { id: 'a1-b15', level: 'A1', category: 'BUSINESS', titleEn: 'Talking About Your Living Place', titleCn: '聊聊你的住处' },
    { id: 'a1-b16', level: 'A1', category: 'BUSINESS', titleEn: 'Describing Your Typical Workday', titleCn: '讲述你的日常工作' },
    { id: 'a1-b17', level: 'A1', category: 'BUSINESS', titleEn: 'Describing Your Workload', titleCn: '描述你的工作量' },
    { id: 'a1-b18', level: 'A1', category: 'BUSINESS', titleEn: 'Talking About Your Spare Time', titleCn: '分享你的业余爱好' },
    { id: 'a1-b19', level: 'A1', category: 'BUSINESS', titleEn: 'Arranging to Meet', titleCn: '约见与预约' },
    { id: 'a1-b20', level: 'A1', category: 'BUSINESS', titleEn: 'Turning Down Arrangements', titleCn: '婉拒会面安排' },
    { id: 'a1-b21', level: 'A1', category: 'BUSINESS', titleEn: 'Buying Train Tickets', titleCn: '买火车票' },
    { id: 'a1-b22', level: 'A1', category: 'BUSINESS', titleEn: 'Reporting Your Work Progress and Achievements', titleCn: '汇报工作进展与成果' },
    { id: 'a1-b23', level: 'A1', category: 'BUSINESS', titleEn: 'Giving an Update', titleCn: '汇报最新进展' },
    { id: 'a1-b24', level: 'A1', category: 'BUSINESS', titleEn: 'Talking about Holiday Trips', titleCn: '谈论假期安排' },
    { id: 'a1-b25', level: 'A1', category: 'BUSINESS', titleEn: 'Replying to Emails and Writing Out-of-Office Emails', titleCn: '回复邮件及撰写休假邮件' },
    { id: 'a1-b26', level: 'A1', category: 'BUSINESS', titleEn: 'Exchanging Information by Phone', titleCn: '打商务电话' },
    { id: 'a1-b27', level: 'A1', category: 'BUSINESS', titleEn: 'Talking about Weather and Climate', titleCn: '聊天气和气候' },
    { id: 'a1-b28', level: 'A1', category: 'BUSINESS', titleEn: 'Making Comparisons', titleCn: '做对比' },
    { id: 'a1-b29', level: 'A1', category: 'BUSINESS', titleEn: 'Making Choices and Decisions', titleCn: '做出选择与决策' },
    { id: 'a1-b30', level: 'A1', category: 'BUSINESS', titleEn: 'Checking in and Boarding at the Airport', titleCn: '办理登机手续和登记' },
    { id: 'a1-b31', level: 'A1', category: 'BUSINESS', titleEn: 'Making Plans', titleCn: '制定计划' },
    { id: 'a1-b32', level: 'A1', category: 'BUSINESS', titleEn: 'Changing Plans', titleCn: '调整计划' },
    { id: 'a1-b33', level: 'A1', category: 'BUSINESS', titleEn: 'Staying at a Hotel', titleCn: '入住酒店' },
    { id: 'a1-b34', level: 'A1', category: 'BUSINESS', titleEn: 'Describing Data and Trend', titleCn: '描述数据和趋势' },
    { id: 'a1-b35', level: 'A1', category: 'BUSINESS', titleEn: 'Talking about Business Performance', titleCn: '讨论业绩表现' },
    { id: 'a1-b36', level: 'A1', category: 'BUSINESS', titleEn: 'Shopping', titleCn: '购物' },

    // =================================================================
    // A2 BUSINESS
    // =================================================================
    { id: 'a2-b1', level: 'A2', category: 'BUSINESS', titleEn: 'Describing Your Job', titleCn: '描述你的工作' },
    { id: 'a2-b2', level: 'A2', category: 'BUSINESS', titleEn: 'Describing Your Company and Departments', titleCn: '介绍公司与部门' },
    { id: 'a2-b3', level: 'A2', category: 'BUSINESS', titleEn: 'Eating Out', titleCn: '外出就餐' },
    { id: 'a2-b4', level: 'A2', category: 'BUSINESS', titleEn: 'Discussing Work in Progress', titleCn: '讨论工作进展' },
    { id: 'a2-b5', level: 'A2', category: 'BUSINESS', titleEn: 'Discussing Strengths and Weaknesses', titleCn: '讨论优缺点与不足' },
    { id: 'a2-b6', level: 'A2', category: 'BUSINESS', titleEn: 'Talking about Your Interests and Hobbies', titleCn: '谈论兴趣与爱好' },
    { id: 'a2-b7', level: 'A2', category: 'BUSINESS', titleEn: 'Making Comparisons', titleCn: '做比较' },
    { id: 'a2-b8', level: 'A2', category: 'BUSINESS', titleEn: 'Describing Your Real Office and Ideal Office', titleCn: '描述真实与理想办公室' },
    { id: 'a2-b9', level: 'A2', category: 'BUSINESS', titleEn: 'Exploring and Recommending Places', titleCn: '推荐与介绍地点' },
    { id: 'a2-b10', level: 'A2', category: 'BUSINESS', titleEn: 'Discussing Personal Work Achievements', titleCn: '讨论个人工作成果' },
    { id: 'a2-b11', level: 'A2', category: 'BUSINESS', titleEn: 'Talking about Teamwork and Team Projects', titleCn: '谈论团队合作与项目' },
    { id: 'a2-b12', level: 'A2', category: 'BUSINESS', titleEn: 'Talking about the Weekend', titleCn: '谈论周末计划' },
    { id: 'a2-b13', level: 'A2', category: 'BUSINESS', titleEn: 'Arranging Meetings', titleCn: '安排会议' },
    { id: 'a2-b14', level: 'A2', category: 'BUSINESS', titleEn: 'Confirming Arrangements', titleCn: '确认会议/差旅安排' },
    { id: 'a2-b15', level: 'A2', category: 'BUSINESS', titleEn: 'Exploring Travel Preferences and Sightseeing Spots', titleCn: '探讨旅行经历与景点' },
    { id: 'a2-b16', level: 'A2', category: 'BUSINESS', titleEn: 'Predicting and Forecasting at Work', titleCn: '预测与预估工作' },
    { id: 'a2-b17', level: 'A2', category: 'BUSINESS', titleEn: 'Talking about Goals', titleCn: '讨论目标' },
    { id: 'a2-b18', level: 'A2', category: 'BUSINESS', titleEn: 'At the Airport', titleCn: '在机场' },
    { id: 'a2-b19', level: 'A2', category: 'BUSINESS', titleEn: 'Talking about Your Education and Career', titleCn: '谈论教育与职业发展' },
    { id: 'a2-b20', level: 'A2', category: 'BUSINESS', titleEn: 'Giving an Update', titleCn: '提供最新进展' },
    { id: 'a2-b21', level: 'A2', category: 'BUSINESS', titleEn: 'Storytelling and Sharing Experiences', titleCn: '讲故事与分享经历' },
    { id: 'a2-b22', level: 'A2', category: 'BUSINESS', titleEn: 'Understanding Business News and Describing Trends', titleCn: '理解商业新闻与趋势' },
    { id: 'a2-b23', level: 'A2', category: 'BUSINESS', titleEn: 'Talking about Economy', titleCn: '讨论经济' },
    { id: 'a2-b24', level: 'A2', category: 'BUSINESS', titleEn: 'Talking About TV Shows', titleCn: '谈论电视节目' },
    { id: 'a2-b25', level: 'A2', category: 'BUSINESS', titleEn: 'Exploring Marketing and Advertising in Business', titleCn: '探讨商务中的市场与广告' },
    { id: 'a2-b26', level: 'A2', category: 'BUSINESS', titleEn: 'Discussing Business Expansion Strategies', titleCn: '讨论业务扩张策略' },
    { id: 'a2-b27', level: 'A2', category: 'BUSINESS', titleEn: 'Tools in the Digital Age', titleCn: '数字化工具的应用' },
    { id: 'a2-b28', level: 'A2', category: 'BUSINESS', titleEn: 'Discussing Ideas and Making Suggestions', titleCn: '提出与讨论建议' },
    { id: 'a2-b29', level: 'A2', category: 'BUSINESS', titleEn: 'Making Decisions', titleCn: '做决策' },
    { id: 'a2-b30', level: 'A2', category: 'BUSINESS', titleEn: 'Dealing with Travel Problems', titleCn: '出差中遇到的问题' },
    { id: 'a2-b31', level: 'A2', category: 'BUSINESS', titleEn: 'Talking About Dimensions', titleCn: '谈论尺寸与规格' },
    { id: 'a2-b32', level: 'A2', category: 'BUSINESS', titleEn: 'Discussing Safety Procedures', titleCn: '讨论安全规范' },
    { id: 'a2-b33', level: 'A2', category: 'BUSINESS', titleEn: 'Using Tourist Facilities On a Cruise', titleCn: '邮轮度假与设施' },
    { id: 'a2-b34', level: 'A2', category: 'BUSINESS', titleEn: 'Attending Meetings', titleCn: '参加会议' },
    { id: 'a2-b35', level: 'A2', category: 'BUSINESS', titleEn: 'Passing on Information', titleCn: '传递信息' },
    { id: 'a2-b36', level: 'A2', category: 'BUSINESS', titleEn: 'Welcoming Visitors and Making Small Talk', titleCn: '接待访客与寒暄' },

    // =================================================================
    // B1 BUSINESS
    // =================================================================
    { id: 'b1-b1', level: 'B1', category: 'BUSINESS', titleEn: 'Talking About Brands', titleCn: '谈论品牌' },
    { id: 'b1-b2', level: 'B1', category: 'BUSINESS', titleEn: 'Sharing Your Opinions in Meetings', titleCn: '在会议中分享观点' },
    { id: 'b1-b3', level: 'B1', category: 'BUSINESS', titleEn: 'Brand Strategy', titleCn: '品牌战略' },
    { id: 'b1-b4', level: 'B1', category: 'BUSINESS', titleEn: 'Taking Flights', titleCn: '谈论航班与差旅' },
    { id: 'b1-b5', level: 'B1', category: 'BUSINESS', titleEn: 'Making Arrangements On the Phone', titleCn: '电话中做安排' },
    { id: 'b1-b6', level: 'B1', category: 'BUSINESS', titleEn: 'Retaining Key Clients', titleCn: '维护核心客户' },
    { id: 'b1-b7', level: 'B1', category: 'BUSINESS', titleEn: 'Adapting to Changes', titleCn: '适应变化' },
    { id: 'b1-b8', level: 'B1', category: 'BUSINESS', titleEn: 'Managing Meetings', titleCn: '管理会议' },
    { id: 'b1-b9', level: 'B1', category: 'BUSINESS', titleEn: 'Solving Problems after a Merger', titleCn: '并购后的问题解决' },
    { id: 'b1-b10', level: 'B1', category: 'BUSINESS', titleEn: 'Company Structure', titleCn: '公司结构' },
    { id: 'b1-b11', level: 'B1', category: 'BUSINESS', titleEn: 'Socializing and Networking', titleCn: '社交与商务人脉' },
    { id: 'b1-b12', level: 'B1', category: 'BUSINESS', titleEn: 'Relocation', titleCn: '公司搬迁' },
    { id: 'b1-b13', level: 'B1', category: 'BUSINESS', titleEn: 'Advertising', titleCn: '广告' },
    { id: 'b1-b14', level: 'B1', category: 'BUSINESS', titleEn: 'Starting and Structuring Presentations', titleCn: '演讲的开场与结构' },
    { id: 'b1-b15', level: 'B1', category: 'BUSINESS', titleEn: 'An advertising Campaign', titleCn: '广告活动' },
    { id: 'b1-b16', level: 'B1', category: 'BUSINESS', titleEn: 'Talking About Finance & Economy', titleCn: '谈论财务与经济' },
    { id: 'b1-b17', level: 'B1', category: 'BUSINESS', titleEn: 'Dealing with Figures & Trends', titleCn: '处理数字和趋势问题' },
    { id: 'b1-b18', level: 'B1', category: 'BUSINESS', titleEn: 'Presenting to Investors', titleCn: '向投资人路演' },
    { id: 'b1-b19', level: 'B1', category: 'BUSINESS', titleEn: 'Culture', titleCn: '跨文化交流' },
    { id: 'b1-b20', level: 'B1', category: 'BUSINESS', titleEn: 'Social English in the Workplace', titleCn: '职场社交英语' },
    { id: 'b1-b21', level: 'B1', category: 'BUSINESS', titleEn: 'Business Culture Briefing', titleCn: '商业文化简报' },
    { id: 'b1-b22', level: 'B1', category: 'BUSINESS', titleEn: 'Recruiting Process and Employment', titleCn: '招聘流程与雇佣' },
    { id: 'b1-b23', level: 'B1', category: 'BUSINESS', titleEn: 'Asking for / Providing Information', titleCn: '索取与提供信息' },
    { id: 'b1-b24', level: 'B1', category: 'BUSINESS', titleEn: 'Appointing the Right Person', titleCn: '人员任命' },
    { id: 'b1-b25', level: 'B1', category: 'BUSINESS', titleEn: 'International Trade and Globalization', titleCn: '国际贸易与全球化' },
    { id: 'b1-b26', level: 'B1', category: 'BUSINESS', titleEn: 'Negotiation Basics', titleCn: '谈判基础' },
    { id: 'b1-b27', level: 'B1', category: 'BUSINESS', titleEn: 'Negotiating a Deal', titleCn: '谈判定案' },
    { id: 'b1-b28', level: 'B1', category: 'BUSINESS', titleEn: 'Ethics in Business', titleCn: '商业道德' },
    { id: 'b1-b29', level: 'B1', category: 'BUSINESS', titleEn: 'Considering Options', titleCn: '评估与选择方案' },
    { id: 'b1-b30', level: 'B1', category: 'BUSINESS', titleEn: 'Ethical Dilemmas', titleCn: '道德困境' },
    { id: 'b1-b31', level: 'B1', category: 'BUSINESS', titleEn: 'Leadership', titleCn: '领导力' },
    { id: 'b1-b32', level: 'B1', category: 'BUSINESS', titleEn: 'Structuring an Entire Presentation', titleCn: '结构化完整演讲' },
    { id: 'b1-b33', level: 'B1', category: 'BUSINESS', titleEn: 'New Leadership', titleCn: '新领导力' },
    { id: 'b1-b34', level: 'B1', category: 'BUSINESS', titleEn: 'Competition', titleCn: '竞争' },
    { id: 'b1-b35', level: 'B1', category: 'BUSINESS', titleEn: 'Negotiating Styles', titleCn: '谈判风格' },
    { id: 'b1-b36', level: 'B1', category: 'BUSINESS', titleEn: 'Negotiating New Contracts', titleCn: '合同谈判' },

    // =================================================================
    // B2 BUSINESS
    // =================================================================
    { id: 'b2-b1', level: 'B2', category: 'BUSINESS', titleEn: 'Effective Communication in Action', titleCn: '高效沟通实战' },
    { id: 'b2-b2', level: 'B2', category: 'BUSINESS', titleEn: 'Dealing with Communication Breakdown', titleCn: '处理沟通障碍' },
    { id: 'b2-b3', level: 'B2', category: 'BUSINESS', titleEn: 'Corporate Communication', titleCn: '企业沟通' },
    { id: 'b2-b4', level: 'B2', category: 'BUSINESS', titleEn: 'Global Marketing Strategies', titleCn: '全球营销战略' },
    { id: 'b2-b5', level: 'B2', category: 'BUSINESS', titleEn: 'Brainstorming', titleCn: '头脑风暴' },
    { id: 'b2-b6', level: 'B2', category: 'BUSINESS', titleEn: 'Global Brand Expansion', titleCn: '全球品牌拓展' },
    { id: 'b2-b7', level: 'B2', category: 'BUSINESS', titleEn: 'Building Business Relationships', titleCn: '构建商务关系' },
    { id: 'b2-b8', level: 'B2', category: 'BUSINESS', titleEn: 'Networking', titleCn: '商务社交网络' },
    { id: 'b2-b9', level: 'B2', category: 'BUSINESS', titleEn: 'Reviving Customer Loyalty', titleCn: '重建客户忠诚度' },
    { id: 'b2-b10', level: 'B2', category: 'BUSINESS', titleEn: 'Navigating Success and Negotiation', titleCn: '导向成功与谈判' },
    { id: 'b2-b11', level: 'B2', category: 'BUSINESS', titleEn: 'Negotiating', titleCn: '商务谈判技巧' },
    { id: 'b2-b12', level: 'B2', category: 'BUSINESS', titleEn: 'Sponsorship Negotiation', titleCn: '商务赞助谈判' },
    { id: 'b2-b13', level: 'B2', category: 'BUSINESS', titleEn: 'Job Satisfaction Insights', titleCn: '工作满意度洞察' },
    { id: 'b2-b14', level: 'B2', category: 'BUSINESS', titleEn: 'Cold-calling', titleCn: '陌拜电话' },
    { id: 'b2-b15', level: 'B2', category: 'BUSINESS', titleEn: 'Employee Relationships', titleCn: '员工关系' },
    { id: 'b2-b16', level: 'B2', category: 'BUSINESS', titleEn: 'Taking Risks and Managing Risks', titleCn: '风险承担与风险管理' },
    { id: 'b2-b17', level: 'B2', category: 'BUSINESS', titleEn: 'Reaching Agreement', titleCn: '达成协议' },
    { id: 'b2-b18', level: 'B2', category: 'BUSINESS', titleEn: 'Risk Management', titleCn: '风险管理' },
    { id: 'b2-b19', level: 'B2', category: 'BUSINESS', titleEn: 'Mastering Management and Presentation Skills', titleCn: '管理与演讲精通' },
    { id: 'b2-b20', level: 'B2', category: 'BUSINESS', titleEn: 'Presentation Basics', titleCn: '管理基础' },
    { id: 'b2-b21', level: 'B2', category: 'BUSINESS', titleEn: 'Strategic Management', titleCn: '战略管理' },
    { id: 'b2-b22', level: 'B2', category: 'BUSINESS', titleEn: 'Teamwork - Collaboration and Conflict', titleCn: '团队协作与冲突管理' },
    { id: 'b2-b23', level: 'B2', category: 'BUSINESS', titleEn: 'Resolving Conflict', titleCn: '冲突解决' },
    { id: 'b2-b24', level: 'B2', category: 'BUSINESS', titleEn: 'Team Dynamics', titleCn: '团队相处之道' },
    { id: 'b2-b25', level: 'B2', category: 'BUSINESS', titleEn: 'The Art of Raising Finance', titleCn: '融资的艺术' },
    { id: 'b2-b26', level: 'B2', category: 'BUSINESS', titleEn: 'Negotiating Styles', titleCn: '谈判风格' },
    { id: 'b2-b27', level: 'B2', category: 'BUSINESS', titleEn: 'Film Financing', titleCn: '影视融资' },
    { id: 'b2-b28', level: 'B2', category: 'BUSINESS', titleEn: 'Mastering Customer Service', titleCn: '客户服务精通' },
    { id: 'b2-b29', level: 'B2', category: 'BUSINESS', titleEn: 'Active Listening', titleCn: '积极聆听' },
    { id: 'b2-b30', level: 'B2', category: 'BUSINESS', titleEn: 'Complaint Resolution', titleCn: '处理投诉' },
    { id: 'b2-b31', level: 'B2', category: 'BUSINESS', titleEn: 'Crisis Management Strategies', titleCn: '危机管理策略' },
    { id: 'b2-b32', level: 'B2', category: 'BUSINESS', titleEn: 'Asking and Answering Difficult Questions', titleCn: '应对棘手问题' },
    { id: 'b2-b33', level: 'B2', category: 'BUSINESS', titleEn: 'Crisis Management', titleCn: '危机处理' },
    { id: 'b2-b34', level: 'B2', category: 'BUSINESS', titleEn: 'Mergers & Acquisitions', titleCn: '并购与收购' },
    { id: 'b2-b35', level: 'B2', category: 'BUSINESS', titleEn: 'Making a Presentation', titleCn: '制作与呈现演讲' },
    { id: 'b2-b36', level: 'B2', category: 'BUSINESS', titleEn: 'Strategic Acquisitions', titleCn: '战略并购' },

    // =================================================================
    // C1 BUSINESS
    // =================================================================
    { id: 'c1-b1', level: 'C1', category: 'BUSINESS', titleEn: 'Teamwork', titleCn: '团队协作与领导' },
    { id: 'c1-b2', level: 'C1', category: 'BUSINESS', titleEn: 'How to deal with a heavy workload', titleCn: '应对繁重工作负荷' },
    { id: 'c1-b3', level: 'C1', category: 'BUSINESS', titleEn: 'Business ethics', titleCn: '商业道德与职业操守' },
    { id: 'c1-b4', level: 'C1', category: 'BUSINESS', titleEn: 'Recruiting & selecting', titleCn: '招聘与人才甄选' },
    { id: 'c1-b5', level: 'C1', category: 'BUSINESS', titleEn: 'Appraising and improving performance', titleCn: '绩效评估与提升' },
    { id: 'c1-b6', level: 'C1', category: 'BUSINESS', titleEn: 'Labor relations', titleCn: '劳资关系管理' },
    { id: 'c1-b7', level: 'C1', category: 'BUSINESS', titleEn: 'Product promotion', titleCn: '产品推广策略' },
    { id: 'c1-b8', level: 'C1', category: 'BUSINESS', titleEn: 'Branding', titleCn: '品牌建设与管理' },
    { id: 'c1-b9', level: 'C1', category: 'BUSINESS', titleEn: 'Keeping customers', titleCn: '客户维护与留存' },
    { id: 'c1-b10', level: 'C1', category: 'BUSINESS', titleEn: 'Mastering internal communication', titleCn: '企业内部沟通' },
    { id: 'c1-b11', level: 'C1', category: 'BUSINESS', titleEn: 'Managing cross-border partnership', titleCn: '跨境合作管理' },
    { id: 'c1-b12', level: 'C1', category: 'BUSINESS', titleEn: 'Interpreting forecasts and results', titleCn: '预测和结果解析' },
    { id: 'c1-b13', level: 'C1', category: 'BUSINESS', titleEn: 'Corporate culture', titleCn: '企业文化' },
    { id: 'c1-b14', level: 'C1', category: 'BUSINESS', titleEn: 'Corporate social responsibility', titleCn: '企业的社会责任' },
    { id: 'c1-b15', level: 'C1', category: 'BUSINESS', titleEn: 'Persuasive influence in busienss', titleCn: '商务说服力' },
    { id: 'c1-b16', level: 'C1', category: 'BUSINESS', titleEn: 'Leading high-performing teams', titleCn: '打造高绩效团队' },
    { id: 'c1-b17', level: 'C1', category: 'BUSINESS', titleEn: 'Going global', titleCn: '全球化布局' },
    { id: 'c1-b18', level: 'C1', category: 'BUSINESS', titleEn: 'Meeting competition', titleCn: '应对竞争策略' },
    { id: 'c1-b19', level: 'C1', category: 'BUSINESS', titleEn: 'Office automation', titleCn: '办公自动化与数字化转型' },
    { id: 'c1-b20', level: 'C1', category: 'BUSINESS', titleEn: 'Internet marketing', titleCn: '互联网营销' },
    { id: 'c1-b21', level: 'C1', category: 'BUSINESS', titleEn: 'Flexible patterns of work', titleCn: '灵活工作模式' },
    { id: 'c1-b22', level: 'C1', category: 'BUSINESS', titleEn: 'Trade fair and exhibitions', titleCn: '展会与商务博览' },
    { id: 'c1-b23', level: 'C1', category: 'BUSINESS', titleEn: 'Paying for self development', titleCn: '自我发展与培训投资' },
    { id: 'c1-b24', level: 'C1', category: 'BUSINESS', titleEn: 'Advertising and consumer psychology', titleCn: '广告和消费心理学' },
    { id: 'c1-b25', level: 'C1', category: 'BUSINESS', titleEn: 'Avoiding culture clashes', titleCn: '避免文化冲突' },
    { id: 'c1-b26', level: 'C1', category: 'BUSINESS', titleEn: 'Giving business updates', titleCn: '商业进展汇报' },
    { id: 'c1-b27', level: 'C1', category: 'BUSINESS', titleEn: 'Finding common ground', titleCn: '寻找共同利益' },
    { id: 'c1-b28', level: 'C1', category: 'BUSINESS', titleEn: 'Gastrodiplomacy', titleCn: '美食外交' },
    { id: 'c1-b29', level: 'C1', category: 'BUSINESS', titleEn: 'Negotiating budget tolerance & error margins', titleCn: '预算容差与误差谈判' },
    { id: 'c1-b30', level: 'C1', category: 'BUSINESS', titleEn: 'Brand collaboration', titleCn: '品牌合作' },
    { id: 'c1-b31', level: 'C1', category: 'BUSINESS', titleEn: 'Strategic decision-making', titleCn: '战略决策制定' },
    { id: 'c1-b32', level: 'C1', category: 'BUSINESS', titleEn: 'Crisis management', titleCn: '危机管理' },
    { id: 'c1-b33', level: 'C1', category: 'BUSINESS', titleEn: 'Stakeholder management', titleCn: '利益相关者管理' },
    { id: 'c1-b34', level: 'C1', category: 'BUSINESS', titleEn: 'Instant pushbacks', titleCn: '即时应对与反驳' },
    { id: 'c1-b35', level: 'C1', category: 'BUSINESS', titleEn: 'Innovation and idea pitching', titleCn: '创新与创意提案' },
    { id: 'c1-b36', level: 'C1', category: 'BUSINESS', titleEn: 'Asking for investment', titleCn: '投资洽谈与融资请求' }
];
